name: price_predictor_chutes
description: AI-powered price prediction tool that combines research from multiple sources to generate detailed price predictions for cryptocurrency and market-related questions.
version: "1.0"
use_cases:
  - Predicting future cryptocurrency prices
  - Analyzing token price movements and trends
  - Forecasting price impacts of market events
  - Technical and fundamental price analysis
example_prompts:
  - "What will be the price of Bitcoin by the end of 2025?"
  - "What is the expected price range for ETH after the next halving?"
  - "How will SOL price react to upcoming token unlocks?"
required_params:
  prompt: string
api_keys:
  openai: string
  perplexity: string
  chutes: string
output_format:
  text: string  # Formatted prediction with scenarios and analysis
  metadata:
    timestamp: string
    query: string
    prediction_horizon: string
    confidence_level: number  # Scale of 1-10
    price_scenarios:
      bull_case:
        price_target: number
        probability: number
        description: string
        key_drivers: array
        technical_levels: array
      base_case:
        price_target: number
        probability: number
        description: string
        key_drivers: array
        technical_levels: array
      bear_case:
        price_target: number
        probability: number
        description: string
        key_drivers: array
        technical_levels: array
    analysis:
      main_drivers:
        type: array
        items:
          factor: string
          price_impact: string
          confidence: number
      technical_levels:
        resistance: array
        support: array
        volume_zones: array
      market_metrics:
        current_price: number
        market_cap: number
        volume_24h: number
        volatility: number
      risk_factors:
        type: array
        items:
          risk: string
          likelihood: number
          price_impact: string 