services:
  - type: web
    name: custom-skills-wip
    env: docker
    region: frankfurt
    rootDir: app
    dockerfilePath: ../deployment/Dockerfile
    branch: main
    healthCheckPath: /
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 300
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAAPI_API_KEY
        sync: false
      - key: DUNE_API_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false 