services:
  - type: web
    name: crypto-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: COINGECKO_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false 