services:
  - type: web
    name: pip-chat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_chat_app:app --bind 0.0.0.0:$PORT --worker-class eventlet
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false 