services:
  - type: web
    name: custom-skills-test
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAAPI_API_KEY
        sync: false
      - key: DUNE_API_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 