name: brian_transaction
description: Generate blockchain transaction calldata based on natural language prompts using Brian API. Supports operations like swapping, bridging, transferring tokens, depositing/withdrawing from DeFi protocols, and ENS domain registration across multiple chains.
version: "1.0"
use_cases:
  - Generating transaction data for token swaps
  - Creating bridge transactions between blockchains
  - Transferring tokens to other addresses
  - Interacting with DeFi protocols (deposit, withdraw)
  - ENS domain registration
example_prompts:
  - "swap 10 USDC for ETH on Base"
  - "bridge 20 USDC from Ethereum to Arbitrum"
  - "transfer 5 ETH to 0x123...456 on Ethereum"
  - "deposit 100 USDC to Aave on Ethereum"
  - "withdraw 50 USDT from Compound"
required_params:
  prompt: string  # Natural language description of the transaction
  address: string # Address that will send the transaction
  chainId: string # Optional: Chain ID of the user (can be inferred from prompt)
api_keys:
  brian: string  # Brian API key for transaction generation
output_format:
  text: string  # Human-readable description of the transaction
  metadata:
    result:
      type: array
      items:
        type: object
        properties:
          solver: string
          action: string
          type: string
          data:
            type: object
            properties:
              description: string
              steps:
                type: array
                items:
                  type: object
                  properties:
                    chainId: integer
                    blockNumber: integer
                    from: string
                    to: string
                    gasLimit: string
                    data: string
                    value: string
              gasCostUSD: string
              fromChainId: integer
              fromAmountUSD: number
              fromAmount: string
              fromToken: object
              toChainId: integer
              toAmountUSD: number
              toAmount: string
              toToken: object
error_messages:
  - "Missing BRIAN_API_KEY environment variable"
  - "Missing required parameter: address"
  - "Error generating transaction. Please check your prompt and try again."
  - "Chain ID could not be determined from the prompt. Please specify chainId explicitly." 