name: technical_analysis
description: Technical Analysis Tool providing comprehensive market analysis using key technical indicators. Focuses on high-probability trade setups with clear entry/exit points and risk management rules.
version: "1.0"
use_cases:
  - Performing detailed technical analysis using multiple indicator categories
  - Identifying high-probability trading setups with precise entry/exit points
  - Analyzing market structure, trends, and key price levels
  - Generating risk-managed trading strategies with clear rules
example_prompts:
  - "Analyze ETH/USDT trend on 4h timeframe with volume confirmation"
  - "Find momentum setups for BTC/USDT using RSI and MACD"
  - "Look for breakout opportunities in SOL/USDT with Bollinger Bands"
  - "Give me scalping setups for BNB/USDT on 5min chart"
required_params:
  prompt: string
api_keys:
  taapi: string
  openai: string
output_format:
  text: string  # Formatted technical analysis with clear trade setups
  metadata:
    symbol: string
    interval: string
    indicators:
      moving_averages:
        sma:
          period_20: number
        ema:
          period_20: number
      trend:
        supertrend:
          value: number
          valueAdvice: string
        adx: number
        dmi:
          adx: number
          pdi: number
          mdi: number
      volume_volatility:
        volume:
          value: number
        stddev:
          value: number
      momentum:
        macd:
          valueMACD: number
          valueMACDSignal: number
          valueMACDHist: number
        rsi:
          value: number
      price:
        bollinger:
          valueUpperBand: number
          valueMiddleBand: number
          valueLowerBand: number
        fibonacci:
          value: number
          trend: string
          startPrice: number
          endPrice: number
          startTimestamp: number
          endTimestamp: number
      ichimoku:
        conversion: number
        base: number
        spanA: number
        spanB: number
        currentSpanA: number
        currentSpanB: number
        laggingSpanA: number
        laggingSpanB: number 