name: general_predictor
description: Advanced prediction tool that analyzes complex scenarios across politics, economics, technology, and society. Combines multiple research sources to generate detailed probabilistic forecasts with scenario analysis.
version: "1.0"
use_cases:
  - Predicting political outcomes and policy changes
  - Forecasting business and economic developments
  - Analyzing social and cultural trends
  - Assessing technological advancements and adoption
  - Evaluating geopolitical scenarios and outcomes
example_prompts:
  - "Who will win the 2024 US presidential election?"
  - "Which tech companies are most likely to face antitrust action in 2024?"
  - "What will be the next major AI breakthrough?"
  - "Who will Trump choose as his VP candidate?"
  - "Which country will be the next to adopt AI regulations?"
required_params:
  prompt: string
api_keys:
  openai: string
  perplexity: string
output_format:
  text: string  # Formatted prediction with scenarios and analysis
  metadata:
    timestamp: string
    query: string
    prediction_horizon: string
    confidence_level: number  # Scale of 1-10
    scenarios:
      optimistic:
        probability: number
        description: string
        key_factors: array
      base:
        probability: number
        description: string
        key_factors: array
      pessimistic:
        probability: number
        description: string
        key_factors: array
    analysis:
      main_drivers:
        type: array
        items:
          factor: string
          impact: string
          confidence: number
      critical_uncertainties:
        type: array
        items:
          factor: string
          potential_impact: string
      supporting_data:
        historical_precedents: array
        current_indicators: array
        expert_opinions: array
      risk_factors:
        type: array
        items:
          risk: string
          likelihood: number
          impact: string 